version: "3.8"

services:
  # web:
  #   depends_on:
  #     - api
  #   build: ./frontend
  #   ports:
  #     - 5173:5173
  #   environment:
  #     VITE_APP_BACKEND_URL: http://localhost:3333

  #   # this is for docker compose watch mode
  #   # anything mentioned under develop will be watched for changes by docker compose watch and it will perform the action mentioned
  #   develop:
  #     # we specify the files to watch for changes
  #     watch:
  #       # it'll watch for changes in package.json and package-lock.json and rebuild the container if there are any changes
  #       - path: ./frontend/package.json
  #         action: rebuild
  #       - path: ./frontend/package-lock.json
  #         action: rebuild
  #       # it'll watch for changes in the frontend directory and sync the changes with the container real time
  #       - path: ./frontend
  #         target: /app
  #         action: sync

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 3333:3333

    environment:
      DB_URL: mongodb://db/fazpay
      NODE_ENV: development
      MONGO_URI: mongodb://db/fazpay
      JWT_SECRET: secret
      CRYPTO_PASSWORD: password

    # establish docker compose watch mode for the api service
    develop:
      # specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container and image if there are any changes
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild

        # it'll watch for changes in the backend directory and sync the changes with the container real time
        - path: ./backend
          target: /app
          action: sync

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: facilita_juridico
    ports:
      - "5432:5432"
    volumes:
      - facilita_juridico:/var/lib/postgresql/data

# define the volumes to be used by the services
volumes:
  facilita_juridico:
