CREATE TABLE IF NOT EXISTS Clients (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  coord_x INTEGER NOT NULL,
  coord_y INTEGER NOT NULL
);